apiVersion: v1
kind: Pod
metadata:
  name: read-only-rootfs
  labels:
    app: read-only-rootfs
spec:
  containers:
  - name: read-only-rootfs
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
    securityContext:
      readOnlyRootFilesystem: true