apiVersion: v1
kind: Pod
metadata:
  name: read-only-rootfs-httpd
  labels:
    app: read-only-rootfs-httpd
spec:
  containers:
  - name: httpd
    image: httpd:2.4.57
    securityContext:
      readOnlyRootFilesystem: true