apiVersion: v1
kind: Pod
metadata:
  name: gvisor-pod
  labels:
    app: gvisor-pod
spec:
  runtimeClassName: gvisor
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]