apiVersion: v1
kind: Pod
metadata:
  name: run-as-user-1000-hello-ng
  labels:
    app: run-as-user-1000-hello-ng
spec:
  containers:
  - name: run-as-user-1000-hello-ng
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do echo hello >> hello.txt;sleep 10; done"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000