apiVersion: v1
kind: Pod
metadata:
  name: run-as-user-1000
  labels:
    app: run-as-user-1000
spec:
  containers:
  - name: run-as-user-1000
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do echo run-as-user-1000;sleep 10; done"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000