apiVersion: v1
kind: Pod
metadata:
  name: exploit-pod
  namespace: ns-psa
spec:
  hostPID: true
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
    securityContext:
      privileged: true