apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend  # SecretStore名
    kind: SecretStore
  target:
    name: sample-secret-from-external-secret  # ExternalSecretから作成するSecret名
  data:
  - secretKey: username
    remoteRef:  # Vaultに登録された秘密情報を指定
      key: /config  # 秘密情報が登録されたパス（SecretStoreで指定したsecretというSecret Engine配下のパスを指定）
      property: username  # 秘密情報のKey
  - secretKey: password
    remoteRef:  # Vaultに登録された秘密情報を指定（SecretStoreで指定したsecretというSecret Engine配下のパスを指定）
      key: /config  # 秘密情報が登録されたパス
      property: password  # 秘密情報のKey