apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-pod
  labels:
    app: sample-secret-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
    env:
    - name: USERNAME  # 環境変数USERNAMEにSecretのusernameに対応する値を設定
      valueFrom:
        secretKeyRef:
          name: sample-secret
          key: username
    - name: PASSWORD  # 環境変数PASSWORDにSecretのpasswordに対応する値を設定
      valueFrom:
        secretKeyRef:
          name: sample-secret
          key: password