apiVersion: v1
kind: Pod
metadata:
  name: default-sa-pod
  labels:
    app: default-sa-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]