apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: sample-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
  serviceAccountName: sample-sa