apiVersion: v1
kind: Pod
metadata:
  name: sample-web
  labels:
    app: sample-web
spec:
  hostPID: true
  containers:
  - name: web
    image: <Docker ID>/sample-web:case1
    securityContext:
      privileged: true